Add delete option
-fully deletes ES

diff --git a/bin/_main b/bin/_main
--- a/bin/_main
+++ b/bin/_main
@@ -118,36 +118,28 @@ elif [ "${1}" == "extract" ]; then
     esac
 elif [ "${1}" == "es" ]; then
     shift
-    if start_es; then
-        if [ "${1}" == "init" ]; then
-            init_es
-        elif [ "${1}" == "rebuild" ]; then
-            reinit_es
-        fi
-        if [ ${EXIT_VAL} == 0 -a "${1}" == "rebuild" ]; then
-            if pushd ${var_run_crucible} >/dev/null; then
-                for base_run_dir in `/bin/ls | grep -v latest`; do
-                    if [ -d "$base_run_dir" ]; then
-                        echo "Going to post-process and index $base_run_dir"
-                        post_process_run "${var_run_crucible}/${base_run_dir}"
-                        index_run "${var_run_crucible}/${base_run_dir}"
-                        this_id=$(extract_run_id "${var_run_crucible}/${base_run_dir}")
-                        get_result_to_file "${base_run_dir}" --run ${this_id}
-                        RC=$?
-                        if [ ${RC} != 0 ]; then
-                            echo "ERROR: Failed to post-process ${base_run_dir} [rc=${RC}]"
-                        fi
-                    fi
-                done
-                popd >/dev/null
-            else
-                echo "ERROR: Could not chdir to ${var_run_crucible}"
-                EXIT_VAL=1
-            fi
-        fi
-    else
-        EXIT_VAL=$?
-    fi
+    start_es || exit_error "Error: could not start ES"
+    case "${1}" in
+        delete)
+            reinit_es || exit_error "Error: could not reinit ES"
+        ;;
+        init)
+            init_es || exit_error "Error: could not init ES"
+        ;;
+        rebuild)
+            reinit_es || exit_error "Error: could not reinit ES"
+            pushd ${var_run_crucible} >/dev/null || exit_error "Error: could not push to ${var_run_crucible}"
+            for base_run_dir in `/bin/ls | grep -v latest`; do
+                if [ -d "$base_run_dir" ]; then
+                    echo "Going to post-process and index $base_run_dir"
+                    post_process_run "${var_run_crucible}/${base_run_dir}" || echo "Error: could not post-process $base_run_dir" && continue
+                    index_run "${var_run_crucible}/${base_run_dir}" || echo "Error: could not index $base_run_dir" && continue
+                    this_id=$(extract_run_id "${var_run_crucible}/${base_run_dir}")
+                    get_result_to_file "${base_run_dir}" --run ${this_id} || echo "Error: could not generate result summary for $base_run_dir" && continue
+                fi
+            done
+        ;;
+    esac
 elif [ "${1}" == "postprocess" ]; then
     shift
     base_run_dir=$(echo "$@" | sed -e "s/--base-run-dir\(\s\+\|=\)//")
